---
name: Checks

on: [push]

jobs:
  test-not-lint:
    name: Test but not Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./src
        run: docker-compose up -d && docker-compose run --rm api sh -c "pytest"
